name:                dater
version:             1.0.0
github:              "wonhyukchoi/dater"
license:             MIT
author:              "Wonhyuk Choi"
maintainer:          "wonhyuk.choi@columbia.edu"
copyright:           "2021 Wonhyuk Choi"
category:            "DSL"
synopsis:            "DSL for date calculation"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wonhyukchoi/dater#readme>

dependencies:
- base >= 4.7 && < 5
- time
- parsec
- mtl
- haskeline
- hspec
- filepath
- directory
- ansi-terminal

library:
  source-dirs: src
  exposed-modules:
    Dater

executables:
  dater:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dater

tests:
  dater-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dater
